export const PatternImages = {
  acceleration: require("!patterns/acceleration.png"),
  basic: require("!patterns/basic.png"),
  circles: require("!patterns/circles.png"),
  coloredTwinkle: require("!patterns/colored-twinkle.png"),
  dim: require("!patterns/dim.png"),
  dimer: require("!patterns/dimer.png"),
  downAndUp: require("!patterns/down-and-up.png"),
  flickerOn: require("!patterns/flicker-on.png"),
  longNoise: require("!patterns/long-noise.png"),
  noise: require("!patterns/noise.png"),
  orangeToPurple: require("!patterns/orange-to-purple.png"),
  rainbowFalls: require("!patterns/rainbow-falls.png"),
  rings: require("!patterns/rings.png"),
  rotatingRings: require("!patterns/rotating-rings.png"),
  rotatingWideRing: require("!patterns/rotating-wide-ring.png"),
  shortNoise: require("!patterns/short-noise.png"),
  simple: require("!patterns/simple.png"),
  tiger: require("!patterns/tiger.png"),
  trifold: require("!patterns/trifold.png"),
  twinkleAll: require("!patterns/twinkle-all.png"),
  veryShortNoise: require("!patterns/very-short-noise.png"),
} as const;
